# Copyright 2020-present, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Davide Abati, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
    'seq-cifar10': {'sgd': {-1: {'lr': 0.1,
                                 'batch_size': 32,
                                 'n_epochs': 50}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                    'coca': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 1.0,
                                     'batch_size': 32,
                                     'n_epochs': 50}},
                    'ocdnet': {
                        200: {
                            'Bernoulli_probability': 0.2,
                            'ER_weight': 0.5,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs':50,
                        },
                        500: {
                            'Bernoulli_probability': 0.2,
                            'ER_weight': 0.5,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs': 50,
                        },
                        5120: {
                            'Bernoulli_probability': 0.8,
                            'ER_weight': 1.0,
                            'lr': 0.1,
                            'minibatch_size': 32,
                            'batch_size': 32,
                            'n_epochs': 50,}},
                },
'seq-cifar100': {'sgd': {-1: {'lr': 0.1,
                                 'batch_size': 32,
                                 'n_epochs': 50}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs':50},
                              5120: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 1.0,
                                     'batch_size': 32,
                                     'n_epochs': 50}},
                 'ocdnet': {
                     200: {
                         'Bernoulli_probability': 0.1,
                         'ER_weight': 0.5,
                         'lr': 0.1,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 50,
                     },
                     500: {
                         'Bernoulli_probability': 0.1,
                         'ER_weight': 0.5,
                         'lr': 0.1,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 50,
                     },
                     2000: {
                         'reg_weight': 0.15,
                         'Bernoulli_probability': 0.2,
                         'ER_weight': 0.5,
                         'lr': 0.1,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 50,
                     },
                     5120: {
                         'reg_weight': 0.15,
                         'Bernoulli_probability': 0.7,
                         'ER_weight': 1.0,
                         'lr': 0.1,
                         'minibatch_size': 32,
                         'batch_size': 32,
                         'n_epochs': 50, }},
                },}
